### ISSUE TITLE
Ability to only download relevant service configurations only based on 

### ISSUE THREAD

**Issue by mpguerra** [3scale/docker-gateway#21]
Currently if you add in the provider key and admin portal, the nginx configuration will be downloaded for ALL services.

Given that we now have admin rights by service which allow us to cherry pick which configurations get downloaded based on the user rights, would it make sense to update the docker image to use access_tokens or provider_key to download the relevant configs.

**Comment by mikz** [comment]
The API does not provide such functionality yet.

**Comment by jmprusi** [comment]
Closing it, we can't implement it right now.

**Comment by andrewdavidmackenzie** [comment]
But it seems a reasonable request - open an issue for the API in System and link this to that issue?

**Comment by mikz** [comment]
@andrewdavidmackenzie there already is.

**Comment by andrewdavidmackenzie** [comment]
5minutes ago, my comment 22 minutes ago - you mean "there is now" ? :-)

**Comment by mikz** [comment]
Nope. 7 days ago. You can see the issue references from the private repo. And we just should delete all this nonsense.
