### ISSUE TITLE
[v2] Missing error message when resolver is not set

### ISSUE THREAD

**Issue by jmprusi** [3scale/docker-gateway#48]
We should output the error message from this part: 
https://github.com/3scale/docker-gateway/blob/v2/src/configuration.lua#L232-L241

We should get a more descriptive message like this: 
````
2016/09/07 22:24:40 [error] 24#24: *1 lua entry thread aborted: runtime error: 
/opt/app/src/configuration.lua:243: no resolver defined to resolve "3scaletesting-admin.3scale.net"
```
instead of:
```2016/09/07 22:16:22 [error] 23#23: *1 lua entry thread aborted: runtime error: /opt/app/src/configuration.lua:193: missing configuration```

**Comment by mikz** [comment]
Now it prints the error message if request failed:

https://github.com/3scale/docker-gateway/blob/a24ae0c61efd378625b5564fd5de7d4f3c46b8f5/src/configuration.lua#L247-L249 (#49)
