### ISSUE TITLE
Rename THREESCALE_ENDPOINT in OpenShift template to THREESCALE_ADMIN_URL

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [3scale/docker-gateway#5]
Rename THREESCALE_ENDPOINT in OpenShift template to THREESCALE_ADMIN_URL as that better described what it is, is more consistent with other references we have - and we tend to reserve the "ENDPOINT" term for our APIs, not for a url of the UI.

Please do this asap and let me know, as the Tutorial text and screenshots all need updating.

**Comment by jmprusi** [comment]
Makes more sense. Done!
