### ISSUE TITLE
Is v2 backwards compatible?

### ISSUE THREAD

**Issue by vorce** [3scale/docker-gateway#63]
We are using `quay.io/3scale/gateway:latest` at the moment, which is from 4 months ago. I'd like to use the `v2` tag (seems to be quite a lot of development). Anything I should be worried about or do before upgrading? Thanks.

**Comment by mikz** [comment]
v2 is now in alpha stage, not every feature has to work. Let me add a note that v2 is not recommended for production use yet. 

But everything will be backwards compatible. The configuration is different, so you have to set one config variable, but then all should work as before.

**Comment by vorce** [comment]
Cheers

**Comment by mikz** [comment]
You can see benefits of using v2 and decide if it it is worth a try: https://github.com/3scale/docker-gateway/pull/66
